### ISSUE TITLE
Confused about Discord's Rich Presence and "self-botting" rules

### ISSUE THREAD

**Issue by cosmicdan** [Vatuu/discord-rpc#11]
Apologies if this isn't the right place (or person) to ask.

I'm interested in making a "bridge" app in Java that hooks into various 3rd-party apps/games to provide rich presence in Discord. Something similar to SimplePresence but my own spin on it (I know noting about JavaScript but enough about JNA).

But I am concerned about Discord's stance on "self-botting" and how it's a bannable offense.

Is Rich Presence something that only game/app developers are allowed to use for their *own* applications? Or is Rich Presence via RPC not considered "self-botting" at all? What do you think?

I've tried to research this as best I can, but am surprised that nobody has really looked into it. Closest thing I found was a request for Rich Presence support in a python.py request, but it was shot-down by someone for being self-botting.

Thanks for any advice you have.

**Comment by cosmicdan** [comment]
You probably got an email of an empty issue with title only, I slipped onto the Enter key by accident - sorry :)

**Comment by Azim** [comment]
i dont remember exatly where i did read it, but there was something very clear about using it only for **your** app and no self-botting.
Since you cant control 3rd party apps, you cant be 100% sure they arent self-bot apps

**Comment by cosmicdan** [comment]
So if that's true, I can't make a rich presence plugin for a music player
(MediaMonkey) to show a playing track?

On the other hand, I saw a Minecraft mod for Hypixel server (a large
multiplayer community) that adds Rich Presence for a game - where some said
it's not allowed, but then a couple others saying "that's only for
self-botting, it doesn't apply to RPC".

Looks like I'll have to get an official statement.

**Comment by cosmicdan** [comment]
I did some more research on the Discord Reddit and it seems to be a
consensus that self-botting is sepcifically the act of automating user
actions. According to the Discord help article "Automated user accounts
(self-bots)" is something that "have full access to all API routes without
using bearer tokens, and can connect to the Real Time Gateway".

Using the RPC is, therefore, not self-botting.

There is a Winamp RPC plugin on Discord Reddit which hasn't been shot down
by anybody, for example.

So unless anybody can find additional information, I'm now quite confident
that the use of RPC is not at all naughty (as long as it's not abused of
course, but that's a different matter).

**Comment by cosmicdan** [comment]
Apologies for the third comment (can't edit comments on mobile), but I found an official statement from https://www.reddit.com/r/discordapp/comments/833qn9/question_are_rpc_selfbots_allowed/

*"custom Rich Presence" is not a violation of our Terms at this time. We don't suggest the practice, through, and this may change at some point in the future.*

So there you go, I should be fine (for now). Of course I need to have my Discord app approved first and all that anyway, but it seems safe for the moment.
