### ISSUE TITLE
Can not share my presence

### ISSUE THREAD

**Issue by FlickySH** [Vatuu/discord-rpc#15]
Made a simple Console app RPC, It works for me but not for everyone else, whitelisted my friend in the project page, but still not working for him

Please reply ASAP

**Comment by Vatuu** [comment]
What exactly do you mean by "not working for anyone else"? What exactly are you trying to achieve?

The whitelist feature is only needed when:
1. You want to test Joining/Spectating within your application.
2. Your application has been greenlit by Discord already, in which case it should work regardless.

**Comment by FlickySH** [comment]
How do I do that, Im pretty new to the discord application mechanism
I have sent my app as a jar to him, he ran it but the presence is not showing.
My friends account is white-listed in the app's page

**Comment by FlickySH** [comment]
The only thing I need is to fix the presence not showing problem I am facing

**Comment by FlickySH** [comment]
EDIT: When sending the source code to him then he compiles it on his computer, it works for some reason,
I seriously don't know what is going on

**Comment by Vatuu** [comment]
Is your friend using a mac?

**Comment by FlickySH** [comment]
No Winodws x64

**Comment by Vatuu** [comment]
How exactly are you packaging it? Are you including the RPC Artifact into your final build, or are you relying on having it provided in the classpath?

**Comment by FlickySH** [comment]
I'm extracting it to the jar, as a dependency

**Comment by Vatuu** [comment]
Try to put your code into a gist or Github Repo. I'll take a look myself.

**Comment by FlickySH** [comment]
Ok
https://gist.github.com/Aregev2/17a1ce8604172719672e4cb34c3d4ebd
(Kotlin)

**Comment by DeJayDev** [comment]
Hi, not here to help but life pro tip:

Those strings "Hover1" and "Hover2" won't show because there no images set to hover.

But seriously,
I feel like it's something with your local build path if he can do it just fine. Are you able to run this without a problem?

**Comment by FlickySH** [comment]
Yes I have removed the presence details, the presence should work, the problem is, it will work on another computers only if the code was compiled on the computer, meaning I can't send my friend an rpc jar to test

**Comment by FlickySH** [comment]
I tried again using Gradle to make a fat Jar but it still didn't work

**Comment by Aregev2** [comment]
Using this library https://github.com/MinnDevelopment/java-discord-rpc works actually

**Comment by DeJayDev** [comment]
Sorry you couldn't setup our library and you had to resort to something less featured/updated. 

Closing this issue.

**Comment by Vatuu** [comment]
Before this seems too rude, you are simply not packaging the dependencies correctly. It works with quite literally everyone else, and you are the first reported case of refusing to work pre-compiled. 

Therefore it has to be a problem on your site, and not in the library.

**Comment by FlickySH** [comment]
Can you help me making the jar properly, I'm using intelliJ idea, Can't figure out what an I doing wrong

**Comment by DeJayDev** [comment]
Message me on Discord, I'm DeJay#1337.
