### ISSUE TITLE
Make end time of game nullable

### ISSUE THREAD

**Issue by 1-alex98** [Vatuu/discord-rpc#18]
If I wanna set start and end time of a game. I am forced to set start and end time by the parameters being long and not Long. Our game https://faforever.com/ does not have a fixed end time, so I want to be able to only set a start time but no end time.

**Comment by Vatuu** [comment]
Sorry for being quite inactive for the last weeks.

Every field inside the DiscordRichPresence object is nullable by default. You can add a start timestamp, and the timer inside the presence will count up. Simply don't assign anything to the end timestamp.

**Comment by 1-alex98** [comment]
https://github.com/Vatuu/discord-rpc/blob/031fe6a9d23cfd42695b9ba9a869da5002217d25/src/main/java/net/arikia/dev/drpc/DiscordRichPresence.java#L40 Sure? long is not nullable right?

**Comment by 1-alex98** [comment]
Ok i got it now so i can set startTime but not endtime. But that is not possible via the Builder.  So it would be good to either split up startTime and endTime in the setTimestamps call or to accept Long instead of long in the Builder, because that was really confusing for me. I thought you would keep variables private if you have a Builder. Whatever thank you very much for your help ;)

**Comment by 1-alex98** [comment]
![image](https://user-images.githubusercontent.com/19996713/43359112-60c39a0e-929d-11e8-9f6c-21997405d9c8.png)
