### ISSUE TITLE
cant run .jar file

### ISSUE THREAD

**Issue by Rozaria** [Vatuu/discord-rpc#19]
![image](https://user-images.githubusercontent.com/41497428/43031460-8723c6c8-8ccc-11e8-8993-b5cfd82b8f22.png)
this error showing if i'm run .bat file on RPCTest folder

**Comment by Vatuu** [comment]
The provided jar is outdated, I'm afraid. I'll update the RPCTest to exclude the bat and pre-build jar, and instead move it to a seperate file inside the release section.

You can always run it from inside IntelliJ too, if you don't want to use the bat file

**Comment by Vatuu** [comment]
It'll be in the next push. (And therefore in the next release)
