### ISSUE TITLE
Cannot acquire Application ID due to new Discord Developer page redesign

### ISSUE THREAD

**Issue by ghost** [Vatuu/discord-rpc#20]
Or more like; how do acquire it. I dont see a way; and using the client ID its not working.

**Comment by Kaleidox00** [comment]
Or more like; how do acquire it. I dont see a way

**Comment by DeJayDev** [comment]
Hey! Please use your client ID and make sure your application has RPC **enabled**.

**Comment by ghost** [comment]
Well, I dont see an option to _disable_ it?

**Comment by Vatuu** [comment]
This really isn't an issue bound to the rpc. Please read up on the documentation and familiarize yourself with discord's developer portal.

**Comment by DeJayDev** [comment]
(@Vatuu is a jerk, if you still genuinely need help message me on Discord. I'm DeJay#1337)
