### ISSUE TITLE
Gradle Support

### ISSUE THREAD

**Issue by DV8FromTheCode** [Vatuu/discord-rpc#21]
Would it be possible to set this up to work with gradle?

**Comment by Vatuu** [comment]
Of course, gradle offers functionality to add maven dependencies to a gradle project.

Simply add the repository, and then add the following line to your dependencies: `compile "net.arikia.dev:discord-rpc:VERSION-YOU-WANT"`.

**Comment by DeJayDev** [comment]
Friendly reminder Jitpack provides specific directions to do this.

https://jitpack.io/#Vatuu/discord-rpc/1.5.0
