### ISSUE TITLE
Documentation is not comprehensive

### ISSUE THREAD

**Issue by ghost** [Vatuu/discord-rpc#22]
The documentation provided in the READ ME is not very comprehensive and is not up-to-date.
Apparently DiscordEventHandler is not in existence, so I cannot get very far.

**Comment by ghost** [comment]
This is in 1.5.1 btw

**Comment by DeJayDev** [comment]
Allow me to notify @Vatuu.

**Comment by DeJayDev** [comment]
Alright!

So I had a talk with Vatuu, send me the version of discord-rpc you're including in your project. If you are unsure show me the dependency snippet from Gradle or Maven and I can assist from there.

**Comment by RedstoneParkour** [comment]
@AwesomeCodePerson Its DiscordEventHandlers
