### ISSUE TITLE
Add start time to Builder

### ISSUE THREAD

**Issue by 1-alex98** [Vatuu/discord-rpc#33]
Can not set startTimestamp via DiscordRichPresence.Builder

**Comment by Vatuu** [comment]
Yes, you can.

https://github.com/Vatuu/discord-rpc/blob/0293d579e74e67d3e118b52c64e9eb392f96c01f/src/main/java/net/arikia/dev/drpc/DiscordRichPresence.java#L121

**Comment by 1-alex98** [comment]
It is new now that I updated version i can see it XD thx sorry for the issue
