### ISSUE TITLE
What about a wrapper of the game sdk?

### ISSUE THREAD

**Issue by 1-alex98** [Vatuu/discord-rpc#36]
Discord Rich Presence is deprecated and was replaced with the game sdk. Would it not be an easy to to the same with that in the way you did it here with Discord Rich Presence sdk.

**Comment by Vatuu** [comment]
This was something I already considered once, however there are two reasons why I haven't done this yet.
1. The rich presence is far from being depricated, it's more of a „light“ game sdk that only covers the rich presence and joining parts.
2. To get access to the developer resources for the Game SDK, one needs to be a verified game developer and purchase a developer license for the discord store. The codebase is under a protected license, which makes it fairly hard to create public wrappers for.

I hope this explains why I haven't done this yet.
Best regards, Vatuu

**Comment by 1-alex98** [comment]
thx for the answer
