### ISSUE TITLE
Typo in README

### ISSUE THREAD

**Issue by noobidev** [Vatuu/discord-rpc#40]
**Describe the bug**
Typo in README

**Source**
Readme

**Error**
```java
public void startup(){
  DiscordEventHandlers handlers = new DiscordEventHandler.Build().setReadyEventHandler((user) -> {
      System.out.println("Welcome " + user.username + "#" + user.discriminator + "!");
  }).build();
  DiscordRPC.initialize("1234567890", handler, true);
}
```
->
```java
public void startup(){
  DiscordEventHandlers handlers = new DiscordEventHandler.Build().setReadyEventHandler((user) -> {
      System.out.println("Welcome " + user.username + "#" + user.discriminator + "!");
  }).build();
  DiscordRPC.initialize("1234567890", handlers, true);
}
```
or
```java
public void startup(){
  DiscordEventHandlers handler = new DiscordEventHandler.Build().setReadyEventHandler((user) -> {
      System.out.println("Welcome " + user.username + "#" + user.discriminator + "!");
  }).build();
  DiscordRPC.initialize("1234567890", handler, true);
}
```

**Versions (Must be completed):**
 - OS Ver: No
 - Java Version: No
 - Library Version: Master branch

**Additional info**
Typo in readme

**Comment by noobidev** [comment]
@DeJayDev... Also change `new DiscordEventHandler.Build()` to `new DiscordEventHandlers.Builder()` because the class is named `DiscordEventHandlers`.

**Comment by Vatuu** [comment]
No need, it's the handler object.

**Comment by noobidev** [comment]
But the class [`DiscordEventHandlers.java`](https://github.com/Vatuu/discord-rpc/blob/master/src/main/java/net/arikia/dev/drpc/DiscordEventHandlers.java) is named `DiscordEventHandlers` 🤔

**Comment by noobidev** [comment]
And it should be `new DiscordEventHandlers.Builder()` because the inner class is `Builder` and not `Build`

**Comment by noobidev** [comment]
@Vatuu @DeJayDev?
