### ISSUE TITLE
presence.setStartTimestamps(created); broken

### ISSUE THREAD

**Issue by ElectronicsBoy** [Vatuu/discord-rpc#53]
**Describe the bug**

When using presence.setStartTimestamps(created);,the bot stops working (I meant it does not sho[a](https://discord.com/developers/docs/rich-presence/how-to#updating-presence-update-presence-payload-fields) [a](https://discord.com/developers/docs/rich-presence/how-to#updating-presence-update-presence-payload-fields) [](https://discord.com/developers/docs/rich-presence/how-to#updating-presence-update-presence-payload-fields) w anything)

**Source**

```java
package io.github.electronicsboy.game.discord;

import net.arikia.dev.drpc.DiscordEventHandlers;
import net.arikia.dev.drpc.DiscordRPC;
import net.arikia.dev.drpc.DiscordRichPresence;
import net.arikia.dev.drpc.DiscordUser;
import net.arikia.dev.drpc.callbacks.ReadyCallback;

public class DiscordRP {
	private boolean running = true;
	private long created = 0;
	
	public void start() {
		this.created = System.currentTimeMillis();
		
		Runtime.getRuntime().addShutdownHook(new Thread(() -> {
            this.shutdown();
        }));
		
		DiscordEventHandlers handlers = new DiscordEventHandlers.Builder().setReadyEventHandler((user) ->  {
            System.out.println("Welcome " + user.username + "#" + user.discriminator + "!");
    		System.out.println("Updating!");
    		
    		DiscordRichPresence.Builder presence = new DiscordRichPresence.Builder("Booting up...");
            presence.setDetails("");
            presence.setStartTimestamps(created);
            DiscordRPC.discordUpdatePresence(presence.build());
    		
        }).build();
		
		DiscordRPC.discordInitialize("837623968734117888", handlers, false);
		DiscordRPC.discordRegister("837623968734117888", "");
		
		new Thread("Discord RPC Callback") {
			public void run() {
				while(running) {
					DiscordRPC.discordRunCallbacks();
				}
			}
		}.start();
	}
	public void shutdown() {
		running = false;
		DiscordRPC.discordShutdown();
	}

	
	public static void update() {
		
	}
```

**Error**

There was no error

**Versions (Must be completed):**
 - OS Ver: Windows 10 latest
 - Java Version: `15.0.0.1`
 - Library Version: `1.6.2`

**Additional info**

none

**Comment by DeJayDev** [comment]
Instead of literally passing how long it's been to the Discord client, pass it an epoch time.

[See here for an example of epoch time from the Discord documentation.](https://discord.com/developers/docs/rich-presence/how-to#updating-presence-update-presence-payload-fields)

**Comment by ElectronicsBoy** [comment]
means? i cant understand

**Comment by ElectronicsBoy** [comment]
i mean what does epoch means?

**Comment by DeJayDev** [comment]
This should be your startTimestamp:

```java
Instant instant = Instant.now();
setStartTimestamp (instant.getEpochSecond());
```

**Comment by ElectronicsBoy** [comment]
ok, will try
