### ISSUE TITLE
Win x64 dll in release JAR seems to be corrupt

### ISSUE THREAD

**Issue by DrinkyBird** [Vatuu/discord-rpc#6]
It seems way too small and refuses to load with the error `Exception in thread "main" java.lang.UnsatisfiedLinkError: F:\Sean\AppData\Local\Temp\discord-rpc.jar\discord-rpc.dll: Can't load IA 32-bit .dll on a AMD 64-bit platform`

**Comment by PierreSchwang** [comment]
Same problem here

**Comment by ricardoboss** [comment]
me too

**Comment by Vatuu** [comment]
This came from a faulty build on discord's site, to use the newly added register methods, I had to build the artifacts from source myself. I'm pushing the fix right now, so everything should be fine again.
