### ISSUE TITLE
Master fails to build

### ISSUE THREAD

**Issue by joshuayuen99** [Vatuu/discord-rpc#63]
**Describe the bug**
Fails to build.

**Error**
```
discord-rpc\src\main\java\net\arikia\dev\drpc\DiscordRPC.java:182:21
java: cannot find symbol
  symbol:   variable f
  location: class net.arikia.dev.drpc.DiscordRPC
```

**Versions (Must be completed):**
 - OS Ver: Windows 10
 - Java Version: 17.0.3
 - Library Version: Master branch

**Additional info**
Looks like commit 1fd4d6931d0ba4d1194851a840418b9ac7a429ff broke this.

**Comment by Vatuu** [comment]
Yeah, I am working on restructuring and cleaning this whole thing up a bit. Until then, just use the releases or an older commit. Sorry about that

**Comment by joshuayuen99** [comment]
No worries! Just wanted to let you know in case you weren't already aware. Thanks for your work on this library.
